# Generated by Django 3.2.18 on 2024-07-05 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='hero_mini_image',
            field=models.ImageField(blank=True, default='hero_mobile.png', null=True, upload_to='hero'),
        ),
        migrations.AddField(
            model_name='product',
            name='hero_mini_text',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='hero_text',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
