# Generated by Django 3.2.18 on 2024-07-05 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_auto_20240705_0958'),
    ]

    operations = [
        migrations.AddField(
            model_name='subcategory',
            name='hot_deal',
            field=models.BooleanField(default=True),
        ),
    ]
