# Generated by Django 3.2.18 on 2024-07-05 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_alter_subcategory_hot_deal'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='list_featured',
            field=models.BooleanField(default=False),
        ),
    ]
