# Generated by Django 3.2.18 on 2024-07-05 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_product_on_sale'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='deal_of_the_week',
            field=models.BooleanField(default=False),
        ),
    ]
