# Generated by Django 3.2.18 on 2024-07-05 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_product_deal_of_the_week'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='fake_stock_qty',
            field=models.IntegerField(default=0),
        ),
    ]
