# Generated by Django 3.2.18 on 2024-07-05 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0009_product_fake_stock_qty'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='deal_of_the_week_end_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
