# Generated by Django 3.2.18 on 2024-07-05 10:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0010_product_deal_of_the_week_end_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='calltoactionbanner',
            name='starting_at_price',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='calltoactionbanner',
            name='subcategory',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='CTA_Banners', to='store.subcategory'),
        ),
    ]
