# Generated by Django 3.2.18 on 2024-07-05 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0011_auto_20240705_1127'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='bestseller',
            field=models.BooleanField(default=False),
        ),
    ]
