# Generated by Django 3.2.18 on 2024-07-05 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0012_category_bestseller'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='home_feature',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='subcategory',
            name='feature_within_category',
            field=models.BooleanField(default=False),
        ),
    ]
