# Generated by Django 3.2.18 on 2024-07-06 10:12

from django.db import migrations, models
import userauths.models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0014_category_featured_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='home_small_box',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='product',
            name='image_small_box',
            field=models.ImageField(blank=True, null=True, upload_to=userauths.models.user_directory_path),
        ),
    ]
