# Generated by Django 3.2.18 on 2024-07-06 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0015_auto_20240706_1112'),
    ]

    operations = [
        migrations.AddField(
            model_name='subcategory',
            name='homepage_feature',
            field=models.BooleanField(default=False),
        ),
    ]
