# Generated by Django 3.2.18 on 2024-07-06 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0016_subcategory_homepage_feature'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subcategory',
            name='homepage_feature',
        ),
        migrations.AddField(
            model_name='category',
            name='upper_half',
            field=models.BooleanField(default=False),
        ),
    ]
