# Generated by Django 3.2.18 on 2024-07-06 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0018_recentlyviewed'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='footer_feature',
            field=models.BooleanField(default=False),
        ),
    ]
