# Generated by Django 3.2.18 on 2024-07-08 11:22

from django.db import migrations
import django_ckeditor_5.fields


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0019_product_footer_feature'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='mini_description',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, null=True),
        ),
    ]
