# Generated by Django 3.2.18 on 2024-07-08 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0021_auto_20240708_1335'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='in_pack',
            field=models.BooleanField(default=False),
        ),
    ]
