# Generated by Django 3.2.18 on 2024-07-09 16:09

from django.db import migrations, models
import userauths.models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0030_product_deal_of_the_week_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='category_feature',
            field=models.ImageField(default='product.png', upload_to=userauths.models.user_directory_path),
        ),
    ]
