# Generated by Django 3.2.18 on 2024-07-10 16:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0032_rename_image_small_box_product_small_box_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='featured_product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='f_c_product', to='store.product'),
        ),
    ]
