# Generated by Django 3.2.18 on 2024-07-12 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0033_alter_category_featured_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='home_featured',
            field=models.BooleanField(default=False),
        ),
    ]
