# Generated by Django 3.2.18 on 2024-08-30 23:52

from django.db import migrations, models
import store.models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0035_auto_20240712_1959'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brand',
            name='image',
            field=models.ImageField(blank=True, default='brand.png', null=True, upload_to=store.models.preserve_filename),
        ),
        migrations.AlterField(
            model_name='calltoactionbanner',
            name='banner',
            field=models.ImageField(default='cta banner.png', upload_to=store.models.preserve_filename),
        ),
        migrations.AlterField(
            model_name='calltoactionbanner',
            name='banner_mobile',
            field=models.ImageField(default='cta monile banner.png', upload_to=store.models.preserve_filename),
        ),
        migrations.AlterField(
            model_name='category',
            name='image',
            field=models.ImageField(blank=True, default='category.png', null=True, upload_to=store.models.preserve_filename),
        ),
        migrations.AlterField(
            model_name='choice',
            name='image',
            field=models.ImageField(blank=True, default='choice.png', null=True, upload_to=store.models.preserve_filename),
        ),
        migrations.AlterField(
            model_name='gallery',
            name='image',
            field=models.ImageField(default='gallery.png', upload_to=store.models.preserve_filename),
        ),
        migrations.AlterField(
            model_name='genre',
            name='featured_image',
            field=models.ImageField(blank=True, default='featured genre.png', null=True, upload_to=store.models.preserve_filename),
        ),
        migrations.AlterField(
            model_name='genre',
            name='image',
            field=models.ImageField(blank=True, default='genre.png', null=True, upload_to=store.models.preserve_filename),
        ),
        migrations.AlterField(
            model_name='product',
            name='category_feature',
            field=models.ImageField(default='product.png', upload_to=store.models.preserve_filename),
        ),
        migrations.AlterField(
            model_name='product',
            name='deal_image',
            field=models.ImageField(blank=True, default='deal.png', null=True, upload_to=store.models.preserve_filename),
        ),
        migrations.AlterField(
            model_name='product',
            name='deal_of_the_week_image',
            field=models.ImageField(default='product.png', upload_to=store.models.preserve_filename),
        ),
        migrations.AlterField(
            model_name='product',
            name='featured_game_banner',
            field=models.ImageField(blank=True, default='featured game banner.png', null=True, upload_to=store.models.preserve_filename),
        ),
        migrations.AlterField(
            model_name='product',
            name='featured_game_slider_banner',
            field=models.ImageField(blank=True, default='featured .png', null=True, upload_to=store.models.preserve_filename),
        ),
        migrations.AlterField(
            model_name='product',
            name='featured_game_slider_mobile_banner',
            field=models.ImageField(blank=True, default='featured game slider mobile banner.png', null=True, upload_to=store.models.preserve_filename),
        ),
        migrations.AlterField(
            model_name='product',
            name='footer_banner',
            field=models.ImageField(default='product.png', upload_to=store.models.preserve_filename),
        ),
        migrations.AlterField(
            model_name='product',
            name='footer_image',
            field=models.ImageField(default='product.png', upload_to=store.models.preserve_filename),
        ),
        migrations.AlterField(
            model_name='product',
            name='hero_banner',
            field=models.ImageField(blank=True, default='hero.png', null=True, upload_to=store.models.preserve_filename),
        ),
        migrations.AlterField(
            model_name='product',
            name='hero_banner_mobile',
            field=models.ImageField(blank=True, default='hero_mobile.png', null=True, upload_to=store.models.preserve_filename),
        ),
        migrations.AlterField(
            model_name='product',
            name='hero_mini_image',
            field=models.ImageField(blank=True, default='hero_mobile.png', null=True, upload_to=store.models.preserve_filename),
        ),
        migrations.AlterField(
            model_name='product',
            name='home_featured_image',
            field=models.ImageField(default='product.png', upload_to=store.models.preserve_filename),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(default='product.png', upload_to=store.models.preserve_filename),
        ),
        migrations.AlterField(
            model_name='product',
            name='small_box_image',
            field=models.ImageField(blank=True, null=True, upload_to=store.models.preserve_filename),
        ),
        migrations.AlterField(
            model_name='product',
            name='small_image',
            field=models.ImageField(default='product.png', upload_to=store.models.preserve_filename),
        ),
        migrations.AlterField(
            model_name='subcategory',
            name='deal_image',
            field=models.ImageField(blank=True, default='deal.png', null=True, upload_to=store.models.preserve_filename),
        ),
        migrations.AlterField(
            model_name='subcategory',
            name='image',
            field=models.ImageField(blank=True, default='sub_category.png', null=True, upload_to=store.models.preserve_filename),
        ),
    ]
