# Generated by Django 3.2.18 on 2024-08-31 06:34

from django.db import migrations, models
import shortuuid.django_fields


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0036_auto_20240830_1652'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='staff_ref',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='sku',
            field=shortuuid.django_fields.ShortUUIDField(alphabet='1234567890', length=5, max_length=20, prefix='SKU', unique=True),
        ),
    ]
