# Generated by Django 3.2.18 on 2024-09-03 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0038_social'),
    ]

    operations = [
        migrations.AlterField(
            model_name='social',
            name='image',
            field=models.ImageField(upload_to='social'),
        ),
    ]
