# Generated by Django 3.2.18 on 2024-09-06 09:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0040_alter_choice_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='type',
            options={'ordering': ['-date'], 'verbose_name_plural': 'types'},
        ),
    ]
