# Generated by Django 3.2.18 on 2024-09-06 09:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0041_alter_type_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='type',
            options={},
        ),
    ]
