# Generated by Django 3.2.18 on 2024-09-08 15:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0045_alter_generalchoice_general_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='choice',
            name='general_choice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='choice', to='store.generalchoice'),
        ),
        migrations.AlterField(
            model_name='generalchoice',
            name='general_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='general_choices', to='store.generaltype'),
        ),
    ]
