# Generated by Django 3.2.18 on 2024-09-08 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0047_alter_choice_general_choice'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='highlight_type',
            field=models.IntegerField(blank=True, choices=[('value', 'Value Of The Day'), ('top', 'TOP 100'), ('new', 'New Arrivals')], null=True),
        ),
    ]
