# Generated by Django 3.2.18 on 2024-09-08 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0048_product_highlight_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='highlight_type',
            field=models.IntegerField(blank=True, choices=[(0, 'Value Of The Day'), (1, 'TOP 100'), (2, 'New Arrivals')], null=True),
        ),
    ]
